export const galleryimages=[
    {
        image:'/Gallery/1.jpg',
        title:''
    },
    {
        image:'/Gallery/2.jpg',
        title:''
    },
    {
        image:'/Gallery/3.jpg',
        title:''
    },
    {
        image:'/Gallery/4.jpg',
        title:''
    },
    {
        image:'/Gallery/5.jpg',
        title:''
    },
    {
        image:'/Gallery/6.jpg',
        title:''
    },
    {
        image:'/Gallery/7.jpg',
        title:''
    },
    {
        image:'/Gallery/8.jpg',
        title:''
    },
    {
        image:'/Gallery/9.jpg',
        title:''
    },
    {
        image:'/Gallery/10.jpg',
        title:''
    },
    {
        image:'/Gallery/11.jpg',
        title:''
    },
    {
        image:'/Gallery/12.jpg',
        title:''
    },
    {
        image:'/Gallery/13.jpg',
        title:''
    },
    {
        image:'/Gallery/14.jpg',
        title:''
    },
    {
        image:'/Gallery/15.jpg',
        title:''
    },
    {
        image:'/Gallery/16.jpg',
        title:''
    },
    {
        image:'/Gallery/17.jpg',
        title:''
    },
    {
        image:'/Gallery/18.jpg',
        title:''
    },
    {
        image:'/Gallery/19.jpg',
        title:''
    },
    {
        image:'/Gallery/20.jpg',
        title:''
    },
    {
        image:'/Gallery/21.jpg',
        title:''
    },
    {
        image:'/Gallery/22.jpg',
        title:''
    },
    {
        image:'/Gallery/23.jpg',
        title:''
    },
    {
        image:'/Gallery/24.jpg',
        title:''
    },
    {
        image:'/Gallery/25.jpg',
        title:''
    },
    {
        image:'/Gallery/26.jpg',
        title:''
    },
    {
        image:'/Gallery/27.jpg',
        title:''
    },
    {
        image:'/Gallery/28.jpg',
        title:''
    },
    {
        image:'/Gallery/29.jpg',
        title:''
    },
    {
        image:'/Gallery/30.jpg',
        title:''
    },
    {
        image:'/Gallery/31.jpg',
        title:''
    },
    {
        image:'/Gallery/32.jpg',
        title:''
    },
    {
        image:'/Gallery/33.jpg',
        title:''
    },
    {
        image:'/Gallery/34.jpg',
        title:''
    },
    {
        image:'/Gallery/35.jpg',
        title:''
    },
    {
        image:'/Gallery/36.jpg',
        title:''
    },
    {
        image:'/Gallery/37.jpg',
        title:''
    },
    {
        image:'/Gallery/38.jpg',
        title:''
    },

]